### ISSUE TITLE
What happened?

### ISSUE THREAD

**Issue by ruizhaoz1** [cryptape/microscope#37]
ruizhaozdeMac:Microscope zxl$ yarn start
yarn run v1.9.4
$ clear && webpack-dev-server --config config/webpack.config.dev.js

Project is running at http://localhost:8080/
webpack output is served from /
404s will fallback to /index.html
Hash: fe4bb5d4fc671caa3b14
Version: webpack 3.12.0
Time: 471917ms
               Asset     Size  Chunks                    Chunk Names
  scripts/1-fe4bb.js  1.89 MB   1, 12  [emitted]  [big]  
  scripts/0-fe4bb.js  3.13 MB   0, 13  [emitted]  [big]  
  scripts/2-fe4bb.js  1.85 MB   2, 16  [emitted]  [big]  
  scripts/3-fe4bb.js  1.84 MB   3, 10  [emitted]  [big]  
  scripts/4-fe4bb.js  1.13 MB    4, 6  [emitted]  [big]  
  scripts/5-fe4bb.js  54.5 kB   5, 11  [emitted]         
  scripts/6-fe4bb.js  39.9 kB       6  [emitted]         
  scripts/7-fe4bb.js  35.5 kB       7  [emitted]         
  scripts/8-fe4bb.js  28.7 kB   8, 15  [emitted]         
  scripts/9-fe4bb.js  14.5 kB   9, 14  [emitted]         
scripts/app-fe4bb.js  6.64 MB     app  [emitted]  [big]  app
 scripts/11-fe4bb.js  5.08 kB      11  [emitted]         
 scripts/12-fe4bb.js  7.09 kB      12  [emitted]         
 scripts/13-fe4bb.js  5.13 kB      13  [emitted]         
 scripts/14-fe4bb.js  7.23 kB      14  [emitted]         
 scripts/15-fe4bb.js  7.67 kB      15  [emitted]         
 scripts/16-fe4bb.js  7.85 kB      16  [emitted]         
 scripts/17-fe4bb.js  5.02 kB      17  [emitted]         
 scripts/18-fe4bb.js  5.84 kB      18  [emitted]         
 scripts/10-fe4bb.js  10.4 kB      10  [emitted]         
          index.html  3.35 kB          [emitted]         
[./node_modules/loglevel/lib/loglevel.js] ./node_modules/loglevel/lib/loglevel.js 7.86 kB {app} [built]
[./node_modules/normalize.css/normalize.css] ./node_modules/normalize.css/normalize.css 1.15 kB {app} [built]
[./node_modules/react-dom/index.js] delegated ../node_modules/react-dom/index.js from dll-reference react_dll 42 bytes {app} [built]
[./node_modules/react-hot-loader/lib/patch.js] ./node_modules/react-hot-loader/lib/patch.js 209 bytes {app} [built]
[./node_modules/react/index.js] delegated ../node_modules/react/index.js from dll-reference react_dll 42 bytes {app} [built]
   [0] multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server webpack/hot/only-dev-server webpack-dev-server/client?http://localhost:8080 react-hot-loader/patch ./src/index.tsx 88 bytes {app} [built]
[./node_modules/react-hot-loader/patch.js] ./node_modules/react-hot-loader/patch.js 40 bytes {app} [built]
[./node_modules/react-i18next/dist/es/index.js] ./node_modules/react-i18next/dist/es/index.js 411 bytes {app} [built]
[./node_modules/strip-ansi/index.js] ./node_modules/strip-ansi/index.js 161 bytes {app} [built]
[./node_modules/url/url.js] ./node_modules/url/url.js 23.3 kB {app} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 7.93 kB {app} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.61 kB {app} [built]
[./node_modules/webpack/hot/only-dev-server.js] (webpack)/hot/only-dev-server.js 2.37 kB {app} [built]
[./src/config/i18n.ts] ./src/config/i18n.ts 1.54 kB {app} [built]
[./src/index.tsx] ./src/index.tsx 1.83 kB {app} [built]
    + 2988 hidden modules

ERROR in ./node_modules/react-hot-loader/webpack.js!./node_modules/ts-loader??ref--0-1!./src/containers/Header/index.tsx
[tsl] ERROR in /Users/zxl/github/Microscope/src/containers/Header/index.tsx(139,21)
      TS2345: Argument of type '{ metadata: { genesisTimestamp: string; chainId: number; chainName: string; operator: string; web...' is not assignable to parameter of type '{ keyword: string; metadata: Metadata; sidebarNavs: boolean; activePanel: string; searchIp: strin...'.
  Type '{ metadata: { genesisTimestamp: string; chainId: number; chainName: string; operator: string; web...' is not assignable to type 'Pick<{ keyword: string; metadata: Metadata; sidebarNavs: boolean; activePanel: string; searchIp: ...'.
    Types of property 'metadata' are incompatible.
      Type '{ genesisTimestamp: string; chainId: number; chainName: string; operator: string; website: string...' is not assignable to type 'Metadata'.
        Property 'version' is missing in type '{ genesisTimestamp: string; chainId: number; chainName: string; operator: string; website: string...'.

ERROR in ./node_modules/bundle-loader?lazy!./src/containers/Header/index.tsx
[tsl] ERROR in /Users/zxl/github/Microscope/src/containers/Header/index.tsx(139,21)
      TS2345: Argument of type '{ metadata: { genesisTimestamp: string; chainId: number; chainName: string; operator: string; web...' is not assignable to parameter of type '{ keyword: string; metadata: Metadata; sidebarNavs: boolean; activePanel: string; searchIp: strin...'.
  Type '{ metadata: { genesisTimestamp: string; chainId: number; chainName: string; operator: string; web...' is not assignable to type 'Pick<{ keyword: string; metadata: Metadata; sidebarNavs: boolean; activePanel: string; searchIp: ...'.
    Types of property 'metadata' are incompatible.
      Type '{ genesisTimestamp: string; chainId: number; chainName: string; operator: string; website: string...' is not assignable to type 'Metadata'.
        Property 'version' is missing in type '{ genesisTimestamp: string; chainId: number; chainName: string; operator: string; website: string...'.
Child html-webpack-plugin for "index.html":
     1 asset
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/templates/index.html] ./node_modules/html-webpack-plugin/lib/loader.js!./src/templates/index.html 3.91 kB {0} [built]
    [./node_modules/lodash/lodash.js] ./node_modules/lodash/lodash.js 540 kB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 509 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 517 bytes {0} [built]
webpack: Failed to compile.

**Comment by Keith-CY** [comment]
It seems that you are working on develop branch, which is for CITA 0.19. 

This error comes for corresponding SDK not released yet.

Although this error will not block the usage of Microscope, master branch is preferable.

**Comment by Keith-CY** [comment]
For this problem a patch has been released, please update code and dependencies to build Microscope for CITA 0.18
